routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TodoController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',[TodoController::class,'index']);
Route::resource('/todo',TodoController::class);
Route::post('todo/destory/bulk',[TodoController::class,'bulkDestroy'])->name('todo.destroy.bulk');
Route::post('todo/edit/bulk',[TodoController::class,'bulkEdit'])->name('todo.edit.bulk');
Route::put('todo/edit/bulk',[TodoController::class,'bulkUpdate'])->name('todo.edit.bulk.submit');

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
    protected $fillable = [
    	'title','todo_id'
    ];
}

app/Models/Todo.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    use HasFactory;
    protected $table = 'todo';
   	protected $fillable = ['name','author','status','priority','due_date'];
   	
   	//items
   	public function items()
   	{
   		return $this->hasMany(Item::class);
   	}



    protected $dates = ['due_date'];
   	protected $casts = [
   		'due_date' => 'date:Y-m-d'
   	];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TodoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Todo;
use App\Models\Item;

class TodoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $todos = Todo::orderBy('priority')->get();
        return view('todo.index',compact('todos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('todo.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(),[
            'name' => 'required',
            'priority' => 'required|numeric'
        ]);

        if ($validator->fails())
            return response()->json(['errors'=>$validator->errors()->all()],422);

        $todo = Todo::create($request->all());

        if ($request->items) {
            foreach($request->items as $item){
                if (empty($item)) continue;
                Item::create([
                    'title'  => $item,
                    'todo_id'   => $todo->id
                ]);
            }
        }

        return response()->json([
            'success' => true,
            'message'=>__('Todo successfully added'),
            'url' => route('todo.index')
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $todo = Todo::findOrFail($id);
        return view('todo.edit',compact('todo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = \Validator::make($request->all(),[
            'name' => 'required',
            'priority' => 'required|numeric'
        ]);

        if ($validator->fails())
            return response()->json(['errors'=>$validator->errors()->all()],422);

        $todo = Todo::findOrFail($id);
        $todo->update($request->all());
        $todo->items()->delete();

        if ($request->items) {
            foreach($request->items as $item){
                if (empty($item)) continue;
                Item::create([
                    'title'  => $item,
                    'todo_id'   => $todo->id
                ]);
            }
                
        }

        return response()->json([
            'success' => true,
            'message'=>__('Todo successfully updated'),
            'url' => route('todo.index')
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $todo = Todo::findOrFail($id);
        $todo->items()->delete();
        $todo->delete();
        return response()->json([
            'message' => 'Todo deleted successfully'
        ]);
    }

    /**
     * [bulkDestroy description]
     * @param  Request $request [description]
     * @return json           [description]
     */     
    public function bulkDestroy(Request $request)
    {
        Item::whereIn('todo_id',$request->ids)->delete();
        Todo::whereIn('id',$request->ids)->delete();
        return response()->json(['message' => 'Todo deleted successfully']);
    }

    /**
     * [bulkEdit description]
     * @param  Request $request [description]
     * @return blade view           [description]
     */
    public function bulkEdit(Request $request)
    {
       $todos = Todo::find($request->ids);
       return view('todo.edit-bulk',compact('todos'));
    }

    /**
     * [bulkUpdate description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function bulkUpdate(Request $request)
    {
        foreach ($request->status as $todo_id => $value) {
            Todo::where('id',$todo_id)->update(['status' => $value]);
        }
        foreach ($request->priority as $todo_id => $value) {
            Todo::where('id',$todo_id)->update(['priority' => $value]);
        }
        return response()->json([
            'message' => 'Todo updated successfully',
            'url'    => route('todo.index')
        ]);
    }
}

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta name="base-url" content="{{ url('/') }}">
    <title>Todo App</title>
    <!-- Bootstrap core CSS -->
    <link href='{{ asset("bootstrap-4.6.0-dist/css/bootstrap.min.css") }}' rel="stylesheet" />
    <script src="{{ asset('js/app.js') }}"></script>
</head>
<body>
    @yield('contents')
</body>
</html>

resources/views/modals/edit-bulk.blade.php
<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalTitle" aria-hidden="true">
  <div class="modal-dialog  modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalTitle">Edit Todo List</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

resources/views/todo/create.blade.php
@extends('layout.app')
@section('contents')
		
	<div class="container my-4">
		<div class="card">
			<div class="card-header">
				Add Todo
				<a href="{{ url()->previous() }}" class="btn btn-sm btn-dark float-right">Back</a>
			</div>
			<div class="card-body">
		    	<form method="POST" class="appForm" action="{{ route('todo.store') }}">
		    		@csrf
		    		<div class="row">
		    			
		    			<div class="col-12 form-group">
		    				<label>Name</label>
		    				<input type="text" class="form-control form-control-sm" name="name"  />
		    			</div>
		    			<div class="col-md-6 form-group">
		    				<label>Author</label>
		    				<input type="text" class="form-control form-control-sm" name="author"  />
		    			</div>
		    			<div class="col-md-6 form-group">
		    				<label>Due Date</label>
		    				<input type="date" class="form-control form-control-sm" name="due_date" value="{{ date('Y-m-d') }}" />
		    			</div>
		    			<div class="col-md-6 form-group">
		    				<label>Status</label>
		    				<input type="text" class="form-control form-control-sm" name="status"   />
		    			</div>
		    			<div class="col-md-6 form-group">
		    				<label>Priority</label>
		    				<input type="number" min="1" class="form-control form-control-sm" name="priority" value="1"  />
		    			</div>

		    			<div class="col-12 form-group ">
		    				Todo Items
		    			</div>

		    			<div class="col-12 itemsContainer">
		    				<div class="input-group mb-1 item">
		    					<div class="input-group-prepend">
								    <div class="input-group-text">
								      <input type="checkbox" aria-label="">
								    </div>
								</div>
							 	<input type="text" name="items[]" class="form-control form-control-sm" placeholder="Item name" >
							  	<div class="input-group-append">
							    	<button class="btn btn-outline-secondary btn-sm deleteItem--btn" type="button" >Delete</button>
							  	</div>
							</div>				
		    			</div>

		    			<div class="col-12">
		    				<button class="btn btn-outline-success btn-sm addItem--btn"  type="button">Add Item</button>
		    				<button class="btn btn-outline-danger btn-sm removeSelected--btn"  type="button" style="display: none;">Remove Selected</button>
		    			</div>

		    		</div>
		    		<div class="appForm--response my-2"></div>
		    		<button class="btn btn-dark btn-sm float-right ">Create</button>
		    	</form>
			</div>
		</div>	
	</div>

@endsection

@section('custom-script')

<script type="text/javascript">
	const App = {
	init() {
        $(document).on('submit','.appForm',App.submitAppForm);
        $(document).on('click','.deleteItem--btn',App.deleteItem);
        $(document).on('click','.addItem--btn',App.addItem);
        $(document).on('click','.deleteRequest--btn',App.deleteRequest);
        $(document).on('click','.deleteRequest--bulk',App.deleteRequestBulk);
        $(document).on('click','.todoCards input[type=checkbox]',App.handleCheckboxClick);
        $(document).on('click','.editRequest--bulk',App.handleBulkEditClick);
        $(document).on('click','.itemsContainer input[type=checkbox]',App.handleItemCheckboxClick);
        $(document).on('click','.removeSelected--btn',App.handleRemoveItemSelected);
	},

    //todos
    //items
    deleteItem() {
        $(this).parent().parent().remove();
    },
    handleItemCheckboxClick() {
        let selectedData = [];
        $(".itemsContainer").find("input[type=checkbox]").each(function(){
            if($(this).is(':checked'))
            selectedData.push($(this).val());
        });
        if(!selectedData.length)
            $('.removeSelected--btn').hide();
        else
            $('.removeSelected--btn').show();
    },
    handleRemoveItemSelected(){
        $(".itemsContainer").find("input[type=checkbox]").each(function(){
            if($(this).is(':checked'))
                $(this).parent().parent().parent().remove();
        });
        $(this).hide();
    },

    addItem(){
        $('.itemsContainer').append(`
            <div class="input-group mb-1 item">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <input type="checkbox" aria-label="">
                    </div>
                </div>
                <input type="text" name="items[]" class="form-control form-control-sm" placeholder="Item name" >
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary btn-sm deleteItem--btn" type="button" >Delete</button>
                </div>
            </div>
        `);
    },


    deleteRequestBulk(){
        let selectedData = [];
        let route = event.target.getAttribute('data-url');

        $(".todoCards").find("input[type=checkbox]").each(function(){
            if($(this).is(':checked'))
            selectedData.push($(this).val());
        });
        if(!selectedData.length){
            alert('Select atleast one card');
            return false;
        }
        if(!confirm('Do you really want to delete?')) return false;
        axios.post(route,{
            ids : selectedData
        }).then((response) => {
            location.reload();
        }).catch((error) => {
            console.error(error);
            alert("Error in deleting contact support");
        });
    },

    handleCheckboxClick() {
        let selectedData = [];
        $(".todoCards").find("input[type=checkbox]").each(function(){
            if($(this).is(':checked'))
            selectedData.push($(this).val());
        });
        if(!selectedData.length)
            $('.deleteRequest--bulk,.editRequest--bulk').hide();
        else
            $('.deleteRequest--bulk,.editRequest--bulk').show();
    },


    handleBulkEditClick(){
        let selectedData = [];
        let route = event.target.getAttribute('data-url');
        let modal = $('#editModal');

        $(".todoCards").find("input[type=checkbox]").each(function(){
            if($(this).is(':checked'))
            selectedData.push($(this).val());
        });
        if(!selectedData.length){
            alert('Select atleast one card');
            return false;
        }
        modal.modal();
        modal.find('.modal-body').html('Loading...');

        axios.post(route, {
          ids : selectedData
        }).then((response) => {
          modal.find('.modal-body').html(response.data)
        }).catch((error) => {
          console.error(error);
        }).finally(() => {
          // TODO
        });

    },

    //global functions
	loader() {
		return '<div class="text-center">  Loading..</div>';
    },

    submitAppForm() {
        event.preventDefault();
		let form = new FormData($('.appForm')[0]);
		let url  = $('.appForm').attr('action');
		let submitBtn = $('.appForm--submit');
		let responseBlock  = $('.appForm--response');
		responseBlock.html(`${App.loader()}`);
		submitBtn.prop('disabled',true);

		axios.post(url,form).then((response) => {
            responseBlock.html(`<div class="alert alert-info successResponse"> ${response.data.message}</div>`);
            if(response.data.url != undefined)
                window.location.href = response.data.url;
    		submitBtn.prop('disabled',false);
        }).catch((error,other) => {
			responseBlock.html('');
			submitBtn.prop('disabled',false);
            error.response.data.errors.map((err) => {
				responseBlock.append(`<div class="alert alert-danger">${err}</div>`) 
			})
        });
    },

    deleteRequest(){
        let route = event.target.getAttribute('data-url');
        let message = event.target.getAttribute('data-message')
        message = message == undefined ? 'Yes, delete it!': message;
        if(confirm(message)){
            axios.delete(route).then((response) => {
                location.reload();
            }).catch((error) => {
                console.error(error);
                alert("Error in deleting contact support");
            });
        }
    },
}
App.init();
</script>
@endsection

resources/views/todo/edit-bulk.blade.php
<form action="{{ route('todo.edit.bulk.submit') }}" class="appForm">
@csrf
@method('PUT')
<div class="row">
	@foreach ($todos as $todo)
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">{{ $todo->name }}</div>
				<div class="card-body">
					<div class="form-group">
						<label>Status</label>
						<input type="text" name="status[{{ $todo->id }}]" class="form-control form-control-sm" value="{{ $todo->status }}">
					</div>
					<div class="form-group">
						<label>Priority</label>
						<input type="number" min="1" name="priority[{{ $todo->id }}]" class="form-control form-control-sm"  value="{{ $todo->priority }}">
					</div>
				</div>
			</div>
		</div>
	@endforeach
	<div class="col-12 my-2 appForm--response"></div>
	<div class="col-12">
		<button class="btn btn-dark btn-submit appForm--submit btn-sm float-right">Update</button>
	</div>
</div>

</form>

resources/views/todo/edit.blade.php
@extends('layout.app')
@section('contents')
		
	<div class="container my-4">
		<div class="card">
			<div class="card-header">
				Edit Todo
				<a href="{{ url()->previous() }}" class="btn btn-sm btn-dark float-right">Back</a>
			</div>
			<div class="card-body">
		    	<form method="POST" class="appForm" action="{{ route('todo.update',$todo->id) }}">
		    		@csrf
		    		@method('PUT')
		    		<div class="row">
		    			
		    			<div class="col-12 form-group">
		    				<label>Name</label>
		    				<input type="text" class="form-control" name="name"  value="{{ $todo->name }}" />
		    			</div>

		    			<div class="col-md-6 form-group">
		    				<label>Author</label>
		    				<input type="text" class="form-control form-control-sm" value="{{ $todo->author }}" name="author"  />
		    			</div>
		    			<div class="col-md-6 form-group">
		    				<label>Due Date</label> 
		    				<input type="date" class="form-control form-control-sm"  value="{{ $todo->due_date->format('Y-m-d') }}" name="due_date"  />
		    			</div>
		    			<div class="col-md-6 form-group">
		    				<label>Status</label>
		    				<input type="text" class="form-control form-control-sm"  value="{{ $todo->status }}" name="status"  />
		    			</div>
		    			<div class="col-md-6 form-group">
		    				<label>Priority</label>
		    				<input type="number" min="1" class="form-control form-control-sm"  value="{{ $todo->priority }}" name="priority"  />
		    			</div>

		    			<div class="col-12 form-group ">
		    				Todo Items
		    			</div>

		    			<div class="col-12 itemsContainer">

		    				@foreach ($todo->items as $item)
		    					<div class="input-group mb-1 item">
		    						<div class="input-group-prepend">
									    <div class="input-group-text">
									      <input type="checkbox" aria-label="">
									    </div>
									</div>
								 	<input type="text" name="items[]" class="form-control form-control-sm" value="{{ $item->title }}">
								 	<div class="input-group-append">
								    	<button class="btn btn-outline-secondary btn-sm deleteItem--btn" type="button" >Delete</button>
								  	</div>
								</div>		
		    				@endforeach

		    				<div class="input-group mb-1 item">
		    					<div class="input-group-prepend">
								    <div class="input-group-text">
								      <input type="checkbox" aria-label="">
								    </div>
								</div>
							 	<input type="text" name="items[]" class="form-control form-control-sm" placeholder="New Item" >
							  	<div class="input-group-append">
							    	<button class="btn btn-outline-secondary btn-sm deleteItem--btn" type="button" >Delete</button>
							  	</div>
							</div>	

		    			</div>

		    			<div class="col-12">
		    				<button class="btn btn-outline-success btn-sm addItem--btn"  type="button">Add Item</button>
		    				<button class="btn btn-outline-danger btn-sm removeSelected--btn"  type="button" style="display: none;">Remove Selected</button>
		    			</div>

		    		</div>
		    		<div class="appForm--response my-2"></div>
		    		<button class="btn btn-dark btn-sm float-right ">Update</button>
		    	</form>
			</div>
		</div>	
	</div>

@endsection

resources/views/todo/index.blade.php
@extends('layout.app')
@section('contents')
		
	<div class="container-fluid my-4" >
		<div class="card shadow" style="min-height:90vh ">
			<div class="card-header">
				Todo List
				<a href="{{ route('todo.create') }}" class="btn btn-sm btn-dark float-right">Add</a>
				<button 
					data-url="{{ route('todo.destroy.bulk') }}"
					class="btn btn-sm btn-danger mx-1 float-right deleteRequest--bulk
					" style="display: none;">Delete Selected</button>
				<button 
					data-url="{{ route('todo.edit.bulk') }}"
					class="btn btn-sm btn-outline-info mx-1 float-right editRequest--bulk
					" style="display: none;">Edit Status/Priority Selected</button>
			</div>
			<div class="card-body ">

				@unless ($todos->count())
					<div class="alert alert-danger">No data found in system</div>
				@endunless

		    	<div class="row todoCards">

		    		@foreach ($todos as $key => $todo)
					<div class="col-lg-4 col-md-6  ">

						<div class="card shadow mb-4">
				  			<div class="card-header">
				  				{{ $todo->name }}

								<span class="badge float-right rounded-0 badge-dark">{{ $todo->status }}</span>
				  				<span class="badge float-right rounded-0 badge-info mx-1">{{ $todo->priority }}</span>
				  				
				  			</div>
					  		<div class="card-body">
			  					<table class="table  text-muted table-sm table-borderless">
			  						<tr><td>Time Left: </td> <td>{{ $todo->due_date->diffForHumans() }}</td><tr>
			  						<tr><td>Due Date: </td> <td>{{ $todo->due_date->format('Y-m-d') }}</td><tr>
			  						<tr><td>Author: </td> <td>{{ $todo->author }}</td><tr>
			  						<tr><td>Created at: </td> <td>{{ $todo->created_at }}</td><tr>
			  						<tr><td>Updated at: </td> <td>{{ $todo->updated_at }}</td><tr>
			  					</table>

					  		</div>
					  		<div class="card-footer p-1">
					  			<span class="border px-2 py-1 text-muted">
					  				<input type="checkbox" id="cp{{ $todo->id }}" value="{{ $todo->id }}" class="mx-2">
					  			<label for="cp{{ $todo->id }}">Select</label>
					  			</span>
					  			<button
						  				data-url="{{ route('todo.destroy',$todo->id) }}"
						  				class="btn btn-sm deleteRequest--btn btn-outline-danger mx-1 float-right "
						  			>Delete</button>

						  			<a
						  				href="{{ route('todo.edit',$todo->id) }}"
						  				class="btn btn-sm btn-outline-info float-right"
						  			>Edit</a>
					  		</div>
				  		</div>

					</div>
		    		@endforeach

				</div>

			</div>
		</div>	
	</div>
@include('modals.edit-bulk')
@endsection